### ISSUE TITLE
[FEAT] 홈페이지

### ISSUE THREAD

**Issue by SEMINSEMINSEMIN** [SEMINSEMINSEMIN/wanted-pre-onboarding-frontend#24]
## Description
<img width="123" alt="스크린샷 2023-04-13 오후 5 52 49" src="https://user-images.githubusercontent.com/104843477/231707438-a903668f-42fb-420e-9ab4-268da90b376d.png">

## Todo
- [x] 로그인 안 했을 때 홈페이지
    - [x] 회원가입 버튼 클릭시 회원가입 페이지로
    - [x] 로그인 버튼 클릭시 로그인 페이지로
- [x] 로그인 했을 때 홈 페이지
    - [x] 나의 투두리스트 버튼 클릭시 투두 페이지로
    - [x] 로그아웃 버튼 클릭시 로컬 스토리지에서 토큰 삭제 및 로그인 안 했을 때 홈페이지로 이동
- [x] 스타일링
