### ISSUE TITLE
[FEAT] 투두리스트 페이지 - 사이드바

### ISSUE THREAD

**Issue by SEMINSEMINSEMIN** [SEMINSEMINSEMIN/wanted-pre-onboarding-frontend#26]
## Description
<img width="228" alt="스크린샷 2023-04-13 오후 8 44 58" src="https://user-images.githubusercontent.com/104843477/231748819-6a69e48f-1a06-4cc8-9b8c-8aea8c063161.png">

## Todo
- [x] 탑바의 사이드바 여는 버튼
- [x] 사이드바 닫기 버튼
- [x] 홈 클릭시 홈페이지로 이동
- [x] 로그아웃 클릭시 로그아웃(로컬 스토리지 삭제, 홈페이지 이동)
