### ISSUE TITLE
[STYLE] reset.css & 색상 변수 & 기타 CSS 맞춤 설정

### ISSUE THREAD

**Issue by SEMINSEMINSEMIN** [SEMINSEMINSEMIN/wanted-pre-onboarding-frontend#9]
### Reset CSS
styled-reset 이용
### 색상 변수 코드
--color-main-solid:  #5B4A92
--color-main-mild: #E1CAEF
--color-main-mild-side: #E1DDF4
--color-solid-gray: #767676
--color-mild-gray: #DBDBDB
--color-text-main: #000000
--color-text-warn: #E41B3F
### 기타 CSS 맞춤 설정
* [rem을 이용한 폰트 사이즈 반응형](https://aboveimagine.tistory.com/85)
    * html 폰트 사이즈를 10px로 설정시, rem 계산시 수월함
    * 그러나 픽셀은 고정된 절대값이므로 접근성에 저해될 수 있음. 유저가 브라우저의 기본 폰트값을 변경하더라도 픽셀값은 변하지 않는다.
    * html 폰트 사이즈를 62.5%로
        * 대부분의 브라우저의 기본 폰트 사이즈가 16px. 16px의 62.5%의 10px이기 때문
* ir class(스크린 리더 사용자 위함)
  ```css
  .ir {
          position: absolute;
	  clip-path: inset(50%);
	  width: 1px;
	  height: 1px;
	  margin: -1px;
	  overflow: hidden;
  }
  ```
* 버튼
    * 커서
        * 활성화: pointer
        * 비활성화: not-allowed
    * border: none
* a 태그
    * text-decoration: none
## Todo
- [x] reset.css
- [x] 색상 변수
- [x] 기타 CSS 맞춤 설정
    - [x] html 폰트 사이즈를 62.5%로
    - [x] box-sizing: border-box
    - [x] .hidden: display: none
    - [x] .ir: 스크린 리더 사용자 위함
    - [x] 버튼
    - [x] a 태그
